runtime: python310
instance_class: F2

handlers:
- url: .*
  script: main.app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  min_idle_instance: automatic
  max_idle_instance: automatic
